/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
 */
public class ANNOTATION_TYPE {
   public static final int POINT = 0; /* Point annotation, fields include name, comm group, lat, lon and color. Clamped to ground. | */
   public static final int CIRCLE = 1; /* Cicle annotation, fields include name, comm group, lat, lon of center, radius, stroke color and fill color. Clamped to ground. | */
   public static final int CYLINDER = 2; /* Cylinder annotation, fields include name, comm group, lat, lon of center, radius, stroke color, fill color, and height (AGL). | */
   public static final int POLYGON = 3; /* Polygon annotation, fields include name, comm group, stroke color, fill color and up to 12 points, lat1, lon1, lat2, lon2, etc. The polygon should be closed between the last defined point and the first defined point. clamped to ground. | */
   public static final int POLYGON_3D = 4; /* 3D Polygon annotation, fields include name, comm group, stroke color, fill color, and up to 12 3d points, lat1, lon1, alt1, lat2, lon2, alt2 etc. The polygon should be closed between the last defined point and the first defined point. Altitudes are AGL. | */
   public static final int POINT_IMAGE = 5; /* Special point annotation that includes an image. Fields include name, comm group, lat, lon, color, full size image url and thumbnail url. Clamped to ground. | */
   public static final int ANNOTATION_TYPE_ENUM_END = 6; /*  | */
}
            