/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * These flags encode elements of state. They are OR-combined flags.
 */
public class ASSET_STATE_FLAG {
   public static final int ASSET_STATE_FLAG_CLUTCHED = 1; /* 0b00000001 Indicate that MAVNet has been overridden by a mode change or mavlink gcs (e.g. declutched). | */
   public static final int ASSET_STATE_FLAG_TETHERED = 2; /* 0b00000010 Indicate that the asset is connected to a cable. | */
   public static final int ASSET_STATE_FLAG_VTOL_CAPABLE = 4; /* 0b00000100 Indicate that the asset is capable of VTOL mode. | */
   public static final int ASSET_STATE_FLAG_VTOL_ENGAGED = 8; /* 0b00001000 Indicate that the asset is operating in VTOL mode. | */
   public static final int ASSET_STATE_FLAG_RESERVED_16 = 16; /* 0b00010000 Reserved for future use. | */
   public static final int ASSET_STATE_FLAG_RESERVED_32 = 32; /* 0b00100000 Reserved for future use. | */
   public static final int ASSET_STATE_FLAG_RESERVED_64 = 64; /* 0b01000000 Reserved for future use. | */
   public static final int ASSET_STATE_FLAG_RESERVED_128 = 128; /* 0b10000000 Reserved for future use. | */
   public static final int ASSET_STATE_FLAG_ENUM_END = 129; /*  | */
}
            