/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
 */
public class COMM_MODE {
   public static final int ACTIVE = 0; /* Interface is in active mode | */
   public static final int STANDBY = 1; /* Interface is in standby (silent) mode | */
   public static final int COMM_MODE_ENUM_END = 2; /*  | */
}
            