/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
        Parameters to be updated on the MAVNet processor.
      
 */
public class MAVNET_PARAM {
   public static final int MAVNET_PARAM_COPTER = 72; /* 
          The core MAVNet params used for copter
         |Radius of the waypoint acceptance criteria in centimeters (0-8000)| Enable (1) or disable (0) the battery failsafe| Battery failsafe voltage in millivolts 0-65535| Enable (1) or disable (0) the geofence| Altitude of the geofence in meters (10-1000)| Radius of the geofence in meters (30-10000)| RTL altitude in centimeters (0-8000)| Enable (1) or disable (0) the hand radio failsafe| Vehicle speed in auto and guided modes in cm/s (20-2000)| Failsafe behavior at EKF failsafe (gps, compass or other sensor failure). 1 = Land, 2 = AltHold, 3 = Land even in Stabilize| Enable (1) or disable (0) the MAVNet rangefinder failsafe. If turned on, then the vehicle will enter brake mode if altitude is less than the specified altitude and the vehicle is in GUIDED mode.| Altitude of the MAVNet rangefinder failsafe in meters (1-200)| Rally point 1 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Altitude above home level, in meters, 0 if unused| Rally point 2 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Altitude above home level, in meters, 0 if unused| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_PARAM_PLANE = 73; /* 
           The core MAVNet params used for planes and quadplanes
         |Radius of the waypoint acceptance criteria in centimeters (0-8000)| Enable (1) or disable (0) the battery failsafe| Battery failsafe voltage in millivolts 0-65535| Enable (1) or disable (0) the geofence| Altitude of the geofence in meters (10-1000)| Radius of the geofence in meters (30-10000)| RTL altitude in centimeters (0-8000)| Enable (1) or disable (0) the hand radio failsafe| Vehicle speed in auto and guided modes in cm/s (20-2000)| Failsafe behavior at EKF failsafe (gps, compass or other sensor failure). 1 = Land, 2 = AltHold, 3 = Land even in Stabilize| Enable (1) or disable (0) the MAVNet rangefinder failsafe. If turned on, then the vehicle will enter brake mode if altitude is less than the specified altitude and the vehicle is in GUIDED mode.| Altitude of the MAVNet rangefinder failsafe in meters (1-200)| Rally point 1 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Altitude above home level, in meters, 0 if unused| Rally point 2 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Altitude above home level, in meters, 0 if unused| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_PARAM_ROVER = 74; /* 
           The core MAVNet params used for rovers
         |Radius of the waypoint acceptance criteria in centimeters (0-8000)| Enable (1) or disable (0) the battery failsafe| Battery failsafe voltage in millivolts 0-65535| Enable (1) or disable (0) the geofence| Ignored| Radius of the geofence in meters (30-10000)| Ignored| Enable (1) or disable (0) the hand radio failsafe| Vehicle speed in auto and guided modes in cm/s (20-2000)| Failsafe Action 0:Nothing, 1:RTL, 2:Hold, 3:SmartRTL or RTL, 4:SmartRTL or Hold| Ignored| Ignored| Rally point 1 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 1 Altitude above home level, in meters, 0 if unused| Rally point 2 Latitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Longitude (WGS84), in degrees * 1E7, 0 if unused| Rally point 2 Altitude above home level, in meters, 0 if unused| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_PARAM_SWITCHBOX = 75; /* 
           The core MAVNet params used for switchboxes
         |Ignored| Enable (1) or disable (0) the battery failsafe| Battery failsafe voltage in millivolts 0-65535| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_PARAM_WEATHERPAK = 76; /* 
           The core MAVNet params used for weatherpaks
         |Ignored| Enable (1) or disable (0) the battery failsafe| Battery failsafe voltage in millivolts 0-65535| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Ignored| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_PARAM_ENUM_END = 77; /*  | */
}
            