/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
        Commands to be executed by the MAVNet processor. 
        They can be executed on user request, or as part of a mission script. 
        If the action is used in a mission, the parameter mapping to the waypoint/mission message is as follows: 
          Param 1, Param 2, Param 3, Param 4, X: Param 5, Y:Param 6, Z:Param 7.
        This format is copied from the MAV_CMD enum.
        Note:
          When a position may be specified, if the lat/lon are given as 0/0 the position should be
          interpreted as NULL.
      
 */
public class MAVNET_CMD {
   public static final int MAVNET_CMD_PAUSE = 5; /* 
          Put the system into a paused state.
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_UNPAUSE = 6; /* 
          Clear the system's paused state.
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_TAKEOFF = 10; /* Takeoff to navigation height and hold position |Empty| Empty| Empty| Takeoff height AHL (Altitude above home level), in meters * 1000 (0 for default)| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_LAND = 11; /* 
          Navigate to the given position and land.
          If the position is NULL, then land in the current location.
         |Empty| Empty| Empty| Empty| Latitude (WGS84), in degrees * 1E7| Longitude (WGS84), in degrees * 1E7| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_ABORT = 12; /* 
          The vehicle will switch to RTL mode and go to the nearest rally point (if specified) 
          or the launch position. Copter vehicles will land when this position is reached.
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_GO_TO = 20; /* Move to a specified position |Empty| Empty| Empty| Start height AHL (Altitude above home level), in meters * 1000 (0 for current)| Latitude (WGS84), in degrees * 1E7| Longitude (WGS84), in degrees * 1E7| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_SET_IMMEDIATE_ALT = 21; /* Set the ImmediateAltitude state to a given value. |Empty| Empty| Empty| Empty| Empty| Empty| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_SET_SPEED = 22; /* 
          Set the desired horizontal navigation speed of the vehicle in decimeters per second.
         |Speed (dm/sec)| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_GO_HOME = 23; /* Move to the lat/lon position where the asset was ARMED |Empty| Empty| Empty| Start height AHL (Altitude above home level), in meters * 1000 (0 for current)| Empty| Empty| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_SET_TARGET_POSITION = 25; /* 
          Set the target position. Position may be NULL to clear the target parameter.
         |Empty| Empty| Empty| Empty| Latitude (WGS84), in degrees * 1E7| Longitude (WGS84), in degrees * 1E7| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_SET_GRIPPER = 26; /* 
          Set the gripper state to hold or release.
         |Gripper state (0=Release, 1=Hold)| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_SWITCH = 27; /* 
          Set the switch state(s) ON or OFF.
         |Switch 1 as in SWITCH_STATE enum (0=OFF, 1=ON, other=IGNORE)| Switch 2 as in SWITCH_STATE enum (0=OFF, 1=ON, other=IGNORE)| Switch 3 as in SWITCH_STATE enum (0=OFF, 1=ON, other=IGNORE)| Switch 4 as in SWITCH_STATE enum (0=OFF, 1=ON, other=IGNORE)| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_FLOW = 28; /* 
          Set the flow rate setpoint in cm^3/min at 0C, 1bar (SCCM).
         |Flow 1 setpoint in SCCM (0=OFF, pos=ON, neg=IGNORE)| Flow 2 setpoint in SCCM (0=OFF, pos=ON, neg=IGNORE)| Flow 3 setpoint in SCCM (0=OFF, pos=ON, neg=IGNORE)| Flow 4 setpoint in SCCM (0=OFF, pos=ON, neg=IGNORE)| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_MISSION_RUN = 50; /* 
          Run the currently loaded mission.
         |Mission sequence number at which to start execution.| Empty| Empty| Start height AHL (Altitude above home level), in meters * 1000 (0 for current)| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_MISSION_STOP = 51; /* 
          Stop the currently running mission.
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_MISSION_CONTINUE = 52; /* 
          Continue the currently loaded mission.
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_HOME_POINT = 60; /* 
          MISSION - Define a home position
         |Empty| Empty| Empty| Empty| Latitude (WGS84), in degrees * 1E7| Longitude (WGS84), in degrees * 1E7| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_SET_RALLY_POINT = 61; /* 
          MISSION - Define a rally point
         |Empty| Empty| Empty| Empty| Latitude (WGS84), in degrees * 1E7| Longitude (WGS84), in degrees * 1E7| AHL (Altitude above home level), in meters * 1000 (positive for up)|  */
   public static final int MAVNET_CMD_DELAY = 62; /* 
          MISSION_LOOP - Delay mission execution for a period of time or indefinitely. 
         |DelayTime (-1: Infinite pause, > 1: delay for the specified period)| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_TARGET_FOLLOW = 63; /* 
          MISSION_LOOP - Set a target system for the mission executor to follow.
         |Target system_id (1-254), 0 clears the follow| Standoff distance (0-1000 meters)| Standoff bearing (rel to true north 0-360)| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_INTERVAL = 64; /* 
          Change the interval of MAVLink messages.  All fields are not applicable to all assets.
         |Message id (0=HEARTBEAT, 255=asset state message, other=as given)| Interval in microseconds| Offset in microseconds| Duration (Integration) time in microseconds| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_COMM_MODE = 65; /* 
          Change the communication mode of various.
         |Line of sight radio (as described by COMM_MODE enum, other=IGNORE)| Internet/Cellular (as described by COMM_MODE enum, other=IGNORE)| Satellite (as described by COMM_MODE enum, other=IGNORE)| Empty| Empty| Empty| State Messages (as described by COMM_MODE enum, other=IGNORE)|  */
   public static final int MAVNET_CMD_IDENTIFY = 70; /* 
          Request a system to send it's COMM_REGISTRATION information
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_VIDEO = 71; /* 
          Request to start or stop a video system.
         |(0=OFF, 1=ON, other=IGNORE)| Camera ID| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_CAMERA_TRIGGER = 72; /* 
          Request to save a still image
         |Camera ID| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_COMPASS_CALIBRATE = 73; /* 
          Start a compass calibration process
         |Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_SET_COMPASS_DEC = 74; /* 
          Sets the compass declination parameter on an ardupilot system
          Range -3.142 3.142, units rad
          increment: 0.01
         |Declination in Radians * 100| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int MAVNET_CMD_ENUM_END = 75; /*  | */
}
            