/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
 */
public class COMM_INTERFACE {
   public static final int LOS = 1; /* Line of sight radio link | */
   public static final int INTERNET = 2; /* Internet (or cellular) link | */
   public static final int SATELLITE = 3; /* Satellite link | */
   public static final int COMM_INTERFACE_ENUM_END = 4; /*  | */
}
            