/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
 * 
 */
public class MAVNET_PARAM_INDEX {
   public static final int wp_radius = 1; /* Radius of the waypoint acceptance criteria in centimeters (0-8000) | */
   public static final int fs_batt_enable = 2; /* Enable (1) or disable (0) the battery failsafe | */
   public static final int fs_batt_voltage = 3; /* Battery failsafe voltage in millivolts 0-65535 | */
   public static final int fence_enable = 4; /* Enable (1) or disable (0) the geofence | */
   public static final int fence_alt_max = 5; /* Altitude of the geofence in meters (10-1000) | */
   public static final int fence_radius = 6; /* Radius of the geofence in meters (30-10000) | */
   public static final int rtl_alt = 7; /* RTL altitude in centimeters (0-8000) | */
   public static final int fs_thr_enable = 8; /* Enable (1) or disable (0) the hand radio failsafe | */
   public static final int wpnav_speed = 9; /* Vehicle speed in auto and guided modes in cm/s (20-2000) | */
   public static final int fs_ekf_action = 10; /* Failsafe behavior at EKF failsafe (gps, compass or other sensor failure). 1 = Land, 2 = AltHold, 3 = Land even in Stabilize | */
   public static final int fs_rangefinder_enable = 11; /* Enable (1) or disable (0) the MAVNet rangefinder failsafe. If turned on, then the vehicle will enter brake mode if altitude is less than the specified altitude and the vehicle is in GUIDED mode. | */
   public static final int fs_rangefinder_alt = 12; /* Altitude of the MAVNet rangefinder failsafe in meters (1-200) | */
   public static final int rally_1_latitude = 13; /* Rally point 1 Latitude (WGS84), in degrees * 1E7, 0 if unused | */
   public static final int rally_1_longitude = 14; /* Rally point 1 Longitude (WGS84), in degrees * 1E7, 0 if unused | */
   public static final int rally_1_ahl = 15; /* Rally point 1 Altitude above home level, in meters, 0 if unused | */
   public static final int rally_2_latitude = 16; /* Rally point 2 Latitude (WGS84), in degrees * 1E7, 0 if unused | */
   public static final int rally_2_longitude = 17; /* Rally point 2 Longitude (WGS84), in degrees * 1E7, 0 if unused | */
   public static final int rally_2_ahl = 18; /* Rally point 2 Altitude above home level, in meters, 0 if unused | */
   public static final int MAVNET_PARAM_INDEX_ENUM_END = 19; /*  | */
}
            