/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ORNL_SET_SYSTEM_MODE PACKING
package com.mavlink.ornl;
import com.mavlink.MAVLinkPacket;
import com.mavlink.Messages.MAVLinkMessage;
import com.mavlink.Messages.MAVLinkPayload;
        
/**
* A message to set the remote system to standby (silent) or active mode.
*/
public class msg_ornl_set_system_mode extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE = 237;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE;


      
    /**
    * System which should execute the command
    */
    public short target_system;
      
    /**
    * Component which should execute the command, 0 for all components
    */
    public short target_component;
      
    /**
    * Current operating mode of the system based on SWITCH_MODE enum
    */
    public short system_mode;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE;
              
        packet.payload.putUnsignedByte(target_system);
              
        packet.payload.putUnsignedByte(target_component);
              
        packet.payload.putUnsignedByte(system_mode);
        
        return packet;
    }

    /**
    * Decode a ornl_set_system_mode message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.target_system = payload.getUnsignedByte();
              
        this.target_component = payload.getUnsignedByte();
              
        this.system_mode = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_ornl_set_system_mode(){
        msgid = MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_ornl_set_system_mode(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE;
        unpack(mavLinkPacket.payload);        
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_ORNL_SET_SYSTEM_MODE -"+" target_system:"+target_system+" target_component:"+target_component+" system_mode:"+system_mode+"";
    }
}
        