/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ARC_PARAMETER PACKING
package com.mavlink.ornl;
import com.mavlink.MAVLinkPacket;
import com.mavlink.Messages.MAVLinkMessage;
import com.mavlink.Messages.MAVLinkPayload;
        
/**
* Send a command with up to twenty parameters to an ArcSoft system.
*/
public class msg_arc_parameter extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_ARC_PARAMETER = 223;
    public static final int MAVLINK_MSG_LENGTH = 83;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ARC_PARAMETER;


      
    /**
    * Parameter 1, as defined by ARC_PARAM enum.
    */
    public int param1;
      
    /**
    * Parameter 2, as defined by ARC_PARAM enum.
    */
    public int param2;
      
    /**
    * Parameter 3, as defined by ARC_PARAM enum.
    */
    public int param3;
      
    /**
    * Parameter 4, as defined by ARC_PARAM enum.
    */
    public int param4;
      
    /**
    * Parameter 5, as defined by ARC_PARAM enum.
    */
    public int param5;
      
    /**
    * Parameter 6, as defined by ARC_PARAM enum.
    */
    public int param6;
      
    /**
    * Parameter 7, as defined by ARC_PARAM enum.
    */
    public int param7;
      
    /**
    * Parameter 8, as defined by ARC_PARAM enum.
    */
    public int param8;
      
    /**
    * Parameter 9, as defined by ARC_PARAM enum.
    */
    public int param9;
      
    /**
    * Parameter 10, as defined by ARC_PARAM enum.
    */
    public int param10;
      
    /**
    * Parameter 11, as defined by ARC_PARAM enum.
    */
    public int param11;
      
    /**
    * Parameter 12, as defined by ARC_PARAM enum.
    */
    public int param12;
      
    /**
    * Parameter 13, as defined by ARC_PARAM enum.
    */
    public int param13;
      
    /**
    * Parameter 14, as defined by ARC_PARAM enum.
    */
    public int param14;
      
    /**
    * Parameter 15, as defined by ARC_PARAM enum.
    */
    public int param15;
      
    /**
    * Parameter 16, as defined by ARC_PARAM enum.
    */
    public int param16;
      
    /**
    * Parameter 17, as defined by ARC_PARAM enum.
    */
    public int param17;
      
    /**
    * Parameter 18, as defined by ARC_PARAM enum.
    */
    public int param18;
      
    /**
    * Parameter 19, as defined by ARC_PARAM enum.
    */
    public int param19;
      
    /**
    * Parameter 20, as defined by ARC_PARAM enum.
    */
    public int param20;
      
    /**
    * Parameter set, as defined by ARC_PARAM enum.
    */
    public int command;
      
    /**
    * System which should execute the command
    */
    public short target_system;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_ARC_PARAMETER;
              
        packet.payload.putInt(param1);
              
        packet.payload.putInt(param2);
              
        packet.payload.putInt(param3);
              
        packet.payload.putInt(param4);
              
        packet.payload.putInt(param5);
              
        packet.payload.putInt(param6);
              
        packet.payload.putInt(param7);
              
        packet.payload.putInt(param8);
              
        packet.payload.putInt(param9);
              
        packet.payload.putInt(param10);
              
        packet.payload.putInt(param11);
              
        packet.payload.putInt(param12);
              
        packet.payload.putInt(param13);
              
        packet.payload.putInt(param14);
              
        packet.payload.putInt(param15);
              
        packet.payload.putInt(param16);
              
        packet.payload.putInt(param17);
              
        packet.payload.putInt(param18);
              
        packet.payload.putInt(param19);
              
        packet.payload.putInt(param20);
              
        packet.payload.putUnsignedShort(command);
              
        packet.payload.putUnsignedByte(target_system);
        
        return packet;
    }

    /**
    * Decode a arc_parameter message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.param1 = payload.getInt();
              
        this.param2 = payload.getInt();
              
        this.param3 = payload.getInt();
              
        this.param4 = payload.getInt();
              
        this.param5 = payload.getInt();
              
        this.param6 = payload.getInt();
              
        this.param7 = payload.getInt();
              
        this.param8 = payload.getInt();
              
        this.param9 = payload.getInt();
              
        this.param10 = payload.getInt();
              
        this.param11 = payload.getInt();
              
        this.param12 = payload.getInt();
              
        this.param13 = payload.getInt();
              
        this.param14 = payload.getInt();
              
        this.param15 = payload.getInt();
              
        this.param16 = payload.getInt();
              
        this.param17 = payload.getInt();
              
        this.param18 = payload.getInt();
              
        this.param19 = payload.getInt();
              
        this.param20 = payload.getInt();
              
        this.command = payload.getUnsignedShort();
              
        this.target_system = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_arc_parameter(){
        msgid = MAVLINK_MSG_ID_ARC_PARAMETER;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_arc_parameter(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_ARC_PARAMETER;
        unpack(mavLinkPacket.payload);        
    }

                                                
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_ARC_PARAMETER -"+" param1:"+param1+" param2:"+param2+" param3:"+param3+" param4:"+param4+" param5:"+param5+" param6:"+param6+" param7:"+param7+" param8:"+param8+" param9:"+param9+" param10:"+param10+" param11:"+param11+" param12:"+param12+" param13:"+param13+" param14:"+param14+" param15:"+param15+" param16:"+param16+" param17:"+param17+" param18:"+param18+" param19:"+param19+" param20:"+param20+" command:"+command+" target_system:"+target_system+"";
    }
}
        