/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MAVNET_STATE_PARAMETERS PACKING
package com.mavlink.mavnet;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;
        
/**
 * A copy of a MAVNet asset's parameters, used to form the param_hash
 */
public class msg_mavnet_state_parameters extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS = 43005;
    public static final int MAVLINK_MSG_LENGTH = 122;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS;


      
    /**
     * Parameter 1, as defined by MAVNET_PARAM enum.
     */
    public int param1;
      
    /**
     * Parameter 2, as defined by MAVNET_PARAM enum.
     */
    public int param2;
      
    /**
     * Parameter 3, as defined by MAVNET_PARAM enum.
     */
    public int param3;
      
    /**
     * Parameter 4, as defined by MAVNET_PARAM enum.
     */
    public int param4;
      
    /**
     * Parameter 5, as defined by MAVNET_PARAM enum.
     */
    public int param5;
      
    /**
     * Parameter 6, as defined by MAVNET_PARAM enum.
     */
    public int param6;
      
    /**
     * Parameter 7, as defined by MAVNET_PARAM enum.
     */
    public int param7;
      
    /**
     * Parameter 8, as defined by MAVNET_PARAM enum.
     */
    public int param8;
      
    /**
     * Parameter 9, as defined by MAVNET_PARAM enum.
     */
    public int param9;
      
    /**
     * Parameter 10, as defined by MAVNET_PARAM enum.
     */
    public int param10;
      
    /**
     * Parameter 11, as defined by MAVNET_PARAM enum.
     */
    public int param11;
      
    /**
     * Parameter 12, as defined by MAVNET_PARAM enum.
     */
    public int param12;
      
    /**
     * Parameter 13, as defined by MAVNET_PARAM enum.
     */
    public int param13;
      
    /**
     * Parameter 14, as defined by MAVNET_PARAM enum.
     */
    public int param14;
      
    /**
     * Parameter 15, as defined by MAVNET_PARAM enum.
     */
    public int param15;
      
    /**
     * Parameter 16, as defined by MAVNET_PARAM enum.
     */
    public int param16;
      
    /**
     * Parameter 17, as defined by MAVNET_PARAM enum.
     */
    public int param17;
      
    /**
     * Parameter 18, as defined by MAVNET_PARAM enum.
     */
    public int param18;
      
    /**
     * Parameter 19, as defined by MAVNET_PARAM enum.
     */
    public int param19;
      
    /**
     * Parameter 20, as defined by MAVNET_PARAM enum.
     */
    public int param20;
      
    /**
     * Parameter 21, as defined by MAVNET_PARAM enum.
     */
    public int param21;
      
    /**
     * Parameter 22, as defined by MAVNET_PARAM enum.
     */
    public int param22;
      
    /**
     * Parameter 23, as defined by MAVNET_PARAM enum.
     */
    public int param23;
      
    /**
     * Parameter 24, as defined by MAVNET_PARAM enum.
     */
    public int param24;
      
    /**
     * Parameter 25, as defined by MAVNET_PARAM enum.
     */
    public int param25;
      
    /**
     * Parameter 26, as defined by MAVNET_PARAM enum.
     */
    public int param26;
      
    /**
     * Parameter 27, as defined by MAVNET_PARAM enum.
     */
    public int param27;
      
    /**
     * Parameter 28, as defined by MAVNET_PARAM enum.
     */
    public int param28;
      
    /**
     * Parameter 29, as defined by MAVNET_PARAM enum.
     */
    public int param29;
      
    /**
     * Parameter 30, as defined by MAVNET_PARAM enum.
     */
    public int param30;
      
    /**
     * Parameter set, as defined by MAVNET_PARAM enum.
     */
    public int definition;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS;
        
        packet.payload.putInt(param1);
        
        packet.payload.putInt(param2);
        
        packet.payload.putInt(param3);
        
        packet.payload.putInt(param4);
        
        packet.payload.putInt(param5);
        
        packet.payload.putInt(param6);
        
        packet.payload.putInt(param7);
        
        packet.payload.putInt(param8);
        
        packet.payload.putInt(param9);
        
        packet.payload.putInt(param10);
        
        packet.payload.putInt(param11);
        
        packet.payload.putInt(param12);
        
        packet.payload.putInt(param13);
        
        packet.payload.putInt(param14);
        
        packet.payload.putInt(param15);
        
        packet.payload.putInt(param16);
        
        packet.payload.putInt(param17);
        
        packet.payload.putInt(param18);
        
        packet.payload.putInt(param19);
        
        packet.payload.putInt(param20);
        
        packet.payload.putInt(param21);
        
        packet.payload.putInt(param22);
        
        packet.payload.putInt(param23);
        
        packet.payload.putInt(param24);
        
        packet.payload.putInt(param25);
        
        packet.payload.putInt(param26);
        
        packet.payload.putInt(param27);
        
        packet.payload.putInt(param28);
        
        packet.payload.putInt(param29);
        
        packet.payload.putInt(param30);
        
        packet.payload.putUnsignedShort(definition);
        
        if(isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a mavnet_state_parameters message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.param1 = payload.getInt();
        
        this.param2 = payload.getInt();
        
        this.param3 = payload.getInt();
        
        this.param4 = payload.getInt();
        
        this.param5 = payload.getInt();
        
        this.param6 = payload.getInt();
        
        this.param7 = payload.getInt();
        
        this.param8 = payload.getInt();
        
        this.param9 = payload.getInt();
        
        this.param10 = payload.getInt();
        
        this.param11 = payload.getInt();
        
        this.param12 = payload.getInt();
        
        this.param13 = payload.getInt();
        
        this.param14 = payload.getInt();
        
        this.param15 = payload.getInt();
        
        this.param16 = payload.getInt();
        
        this.param17 = payload.getInt();
        
        this.param18 = payload.getInt();
        
        this.param19 = payload.getInt();
        
        this.param20 = payload.getInt();
        
        this.param21 = payload.getInt();
        
        this.param22 = payload.getInt();
        
        this.param23 = payload.getInt();
        
        this.param24 = payload.getInt();
        
        this.param25 = payload.getInt();
        
        this.param26 = payload.getInt();
        
        this.param27 = payload.getInt();
        
        this.param28 = payload.getInt();
        
        this.param29 = payload.getInt();
        
        this.param30 = payload.getInt();
        
        this.definition = payload.getUnsignedShort();
        
        if(isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mavnet_state_parameters() {
        msgid = MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS;
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mavnet_state_parameters(MAVLinkPacket mavLinkPacket) {
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);        
    }

                                                                  
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_MAVNET_STATE_PARAMETERS - sysid:"+sysid+" compid:"+compid+" param1:"+param1+" param2:"+param2+" param3:"+param3+" param4:"+param4+" param5:"+param5+" param6:"+param6+" param7:"+param7+" param8:"+param8+" param9:"+param9+" param10:"+param10+" param11:"+param11+" param12:"+param12+" param13:"+param13+" param14:"+param14+" param15:"+param15+" param16:"+param16+" param17:"+param17+" param18:"+param18+" param19:"+param19+" param20:"+param20+" param21:"+param21+" param22:"+param22+" param23:"+param23+" param24:"+param24+" param25:"+param25+" param26:"+param26+" param27:"+param27+" param28:"+param28+" param29:"+param29+" param30:"+param30+" definition:"+definition+"";
    }
}
        