/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MAVNET_STATE_WEATHERPAK PACKING
package com.mavlink.mavnet;
import com.mavlink.MAVLinkPacket;
import com.mavlink.messages.MAVLinkMessage;
import com.mavlink.messages.MAVLinkPayload;
        
/**
 * Data from the MAVNet Weather station interface.
 */
public class msg_mavnet_state_weatherpak extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK = 43015;
    public static final int MAVLINK_MSG_LENGTH = 138;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK;


      
    /**
     * Incrementing sequence number, device is expected to increment with each msg and not repeat even with reboot
     */
    public long state_sequence;
      
    /**
     * Timestamp (UNIX epoch based on GPS)
     */
    public long time_usec;
      
    /**
     * Provides information on the current executing command on the device
     */
    public long command_sequence;
      
    /**
     * Estimate of remaining operation time (0: no estimate, 0xFFFFFFFF: no battery)
     */
    public long estimated_run_time;
      
    /**
     * The interval between each STATE message
     */
    public int interval;
      
    /**
     * The delay between sensor integrations
     */
    public int offset;
      
    /**
     * The amount of time to integrate sensor data
     */
    public int duration;
      
    /**
     * Latitude (WGS84)
     */
    public int latitude;
      
    /**
     * Longitude (WGS84)
     */
    public int longitude;
      
    /**
     * Altitude above mean sea level (positive for up)
     */
    public int altitude_amsl;
      
    /**
     * The weather sensor unit serial number
     */
    public long serial_number;
      
    /**
     * Integrated wind speed in (m/s)
     */
    public float wind_speed;
      
    /**
     * Integrated wind direction (degrees)
     */
    public float wind_direction;
      
    /**
     * Wind standard deviation
     */
    public float wind_std_dev;
      
    /**
     * Current orientation in degrees, in compass units (0..360, 0=north)
     */
    public float magnet_heading;
      
    /**
     * Barometric pressure (hectopascal)
     */
    public float press_abs;
      
    /**
     * Relative humidity (percent)
     */
    public float relative_humidity;
      
    /**
     * Battery voltage (0: no information)
     */
    public int voltage_battery;
      
    /**
     * CPU [0], Board [1] temperature (Celsius)
     */
    public short system_temperature[] = new short[16];
      
    /**
     * Integrated/average temperature measurement (Celsius)
     */
    public short temperature;
      
    /**
     * Type of the MAV defined in MAV_TYPE ENUM, Added so this message can be used standalone in LB environments
     */
    public short system_type;
      
    /**
     * System id of the device to which we wish to subscribe. (0: none, 255: all)
     */
    public short subscription;
      
    /**
     * Hash of the currently loaded parameters (MD5 hash)
     */
    public short param_hash[] = new short[16];
      
    /**
     * The interface transmitting this message
     */
    public byte transmit_interface;
      
    /**
     * LOS availability and signal strength. (-2: Faulted, -1: Disabled, 0-100: signal strength)
     */
    public byte los_rssi;
      
    /**
     * LOS availability and signal strength. (-2: Faulted, -1: Disabled, 0-100: signal strength)
     */
    public byte cellular_rssi;
      
    /**
     * LOS availability and signal strength. (-2: Faulted, -1: Disabled, 0-100: signal strength)
     */
    public byte satellite_rssi;
      
    /**
     * See the GPS_FIX_TYPE enum.
     */
    public short gps_fix_type;
      
    /**
     * Number of satellites visible. If unknown, set to 255
     */
    public short gps_satellites_visible;
      
    /**
     * Remaining battery energy, -1: not available
     */
    public byte battery_remaining;
      
    /**
     * Current operating mode of the system based on SWITCH_MODE enum
     */
    public short system_mode;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = 255;
        packet.compid = 190;
        packet.msgid = MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK;
        
        packet.payload.putLong(state_sequence);
        
        packet.payload.putUnsignedLong(time_usec);
        
        packet.payload.putUnsignedInt(command_sequence);
        
        packet.payload.putUnsignedInt(estimated_run_time);
        
        packet.payload.putInt(interval);
        
        packet.payload.putInt(offset);
        
        packet.payload.putInt(duration);
        
        packet.payload.putInt(latitude);
        
        packet.payload.putInt(longitude);
        
        packet.payload.putInt(altitude_amsl);
        
        packet.payload.putUnsignedInt(serial_number);
        
        packet.payload.putFloat(wind_speed);
        
        packet.payload.putFloat(wind_direction);
        
        packet.payload.putFloat(wind_std_dev);
        
        packet.payload.putFloat(magnet_heading);
        
        packet.payload.putFloat(press_abs);
        
        packet.payload.putFloat(relative_humidity);
        
        packet.payload.putUnsignedShort(voltage_battery);
        
        
        for (int i = 0; i < system_temperature.length; i++) {
            packet.payload.putShort(system_temperature[i]);
        }
                    
        
        packet.payload.putShort(temperature);
        
        packet.payload.putUnsignedByte(system_type);
        
        packet.payload.putUnsignedByte(subscription);
        
        
        for (int i = 0; i < param_hash.length; i++) {
            packet.payload.putUnsignedByte(param_hash[i]);
        }
                    
        
        packet.payload.putByte(transmit_interface);
        
        packet.payload.putByte(los_rssi);
        
        packet.payload.putByte(cellular_rssi);
        
        packet.payload.putByte(satellite_rssi);
        
        packet.payload.putUnsignedByte(gps_fix_type);
        
        packet.payload.putUnsignedByte(gps_satellites_visible);
        
        packet.payload.putByte(battery_remaining);
        
        packet.payload.putUnsignedByte(system_mode);
        
        if(isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a mavnet_state_weatherpak message into this class fields
     *
     * @param payload The message to decode
     */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
        
        this.state_sequence = payload.getLong();
        
        this.time_usec = payload.getUnsignedLong();
        
        this.command_sequence = payload.getUnsignedInt();
        
        this.estimated_run_time = payload.getUnsignedInt();
        
        this.interval = payload.getInt();
        
        this.offset = payload.getInt();
        
        this.duration = payload.getInt();
        
        this.latitude = payload.getInt();
        
        this.longitude = payload.getInt();
        
        this.altitude_amsl = payload.getInt();
        
        this.serial_number = payload.getUnsignedInt();
        
        this.wind_speed = payload.getFloat();
        
        this.wind_direction = payload.getFloat();
        
        this.wind_std_dev = payload.getFloat();
        
        this.magnet_heading = payload.getFloat();
        
        this.press_abs = payload.getFloat();
        
        this.relative_humidity = payload.getFloat();
        
        this.voltage_battery = payload.getUnsignedShort();
        
         
        for (int i = 0; i < this.system_temperature.length; i++) {
            this.system_temperature[i] = payload.getShort();
        }
                
        
        this.temperature = payload.getShort();
        
        this.system_type = payload.getUnsignedByte();
        
        this.subscription = payload.getUnsignedByte();
        
         
        for (int i = 0; i < this.param_hash.length; i++) {
            this.param_hash[i] = payload.getUnsignedByte();
        }
                
        
        this.transmit_interface = payload.getByte();
        
        this.los_rssi = payload.getByte();
        
        this.cellular_rssi = payload.getByte();
        
        this.satellite_rssi = payload.getByte();
        
        this.gps_fix_type = payload.getUnsignedByte();
        
        this.gps_satellites_visible = payload.getUnsignedByte();
        
        this.battery_remaining = payload.getByte();
        
        this.system_mode = payload.getUnsignedByte();
        
        if(isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_mavnet_state_weatherpak() {
        msgid = MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK;
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_mavnet_state_weatherpak(MAVLinkPacket mavLinkPacket) {
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);        
    }

                                                                  
    /**
     * Returns a string with the MSG name and data
     */
    public String toString() {
        return "MAVLINK_MSG_ID_MAVNET_STATE_WEATHERPAK - sysid:"+sysid+" compid:"+compid+" state_sequence:"+state_sequence+" time_usec:"+time_usec+" command_sequence:"+command_sequence+" estimated_run_time:"+estimated_run_time+" interval:"+interval+" offset:"+offset+" duration:"+duration+" latitude:"+latitude+" longitude:"+longitude+" altitude_amsl:"+altitude_amsl+" serial_number:"+serial_number+" wind_speed:"+wind_speed+" wind_direction:"+wind_direction+" wind_std_dev:"+wind_std_dev+" magnet_heading:"+magnet_heading+" press_abs:"+press_abs+" relative_humidity:"+relative_humidity+" voltage_battery:"+voltage_battery+" system_temperature:"+system_temperature+" temperature:"+temperature+" system_type:"+system_type+" subscription:"+subscription+" param_hash:"+param_hash+" transmit_interface:"+transmit_interface+" los_rssi:"+los_rssi+" cellular_rssi:"+cellular_rssi+" satellite_rssi:"+satellite_rssi+" gps_fix_type:"+gps_fix_type+" gps_satellites_visible:"+gps_satellites_visible+" battery_remaining:"+battery_remaining+" system_mode:"+system_mode+"";
    }
}
        