/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
* 
*/
public class SWITCH_STATE {
   public static final int OFF = 0; /* Device is OFF | */
   public static final int ON = 1; /* Device is ON | */
   public static final int SWITCH_STATE_ENUM_END = 2; /*  | */
}
            