/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
* 
        Parameters to be updated on the ArcSoft processor.
        They are executed apart from the normal command stream and are used during setup and preparation of the asset.
      
*/
public class ARC_PARAM {
   public static final int ARC_PARAM_SET_PARAM_COMPASS_DEC = 71; /* 
          Sets the compass declination parameter on an ardupilot system
          Range -3.142 3.142, units rad
          increment: 0.01
         |Declination in Radians * 100| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty| Empty|  */
   public static final int ARC_PARAM_ENUM_END = 72; /*  | */
}
            