/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.mavlink.enums;

/** 
* ORNL specific device type
*/
public class ORNL_SYSTEM_TYPE {
   public static final int ORNL_SYSTEM_TYPE_SUBSCRIBER = 0; /* Subscriber systems such as a ground control station comm stack | */
   public static final int ORNL_SYSTEM_TYPE_PUBLISHER = 1; /* Publisher systems such as an unmanned vehicle or sensor | */
   public static final int ORNL_SYSTEM_TYPE_ENUM_END = 2; /*  | */
}
            